# .github/workflows/norminette.yml
name: norminette_V3
on:
  push:
    branches:
      - main
      - parsing
jobs:

  norminette_v3_job:
    runs-on: ubuntu-latest
    name: norminette
    steps:
    - uses: actions/checkout@v3
    - uses: alexandregv/norminette-action@v3
